services:
  api:
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    env_file:
      - .env
    environment:
      - DEBUG=true
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    profiles:
      - dev

  redis:
    image: redis:latest
    command: redis-server --save 60 1 --loglevel warning
    healthcheck:
      test: bash -c "redis-cli -a ping"
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    profiles:
      - dev
