services:
  api:
    build: .
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "4"]
    env_file:
      - .env.production
    profiles:
      - prod

  redis:
    image: redis:alpine
    command: redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env.production
    profiles:
      - prod
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
