# fly.toml app configuration file generated for omniview-api on 2025-05-02T15:02:39-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'omniview-api'
primary_region = 'dfw'

[build]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'false'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[http_service.concurrency]
  type = "connections"
  hard_limit = 100
  soft_limit = 50

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[services.tcp_checks]
  interval = "10s"
  timeout = "2s"
  grace_period = "30s"
